Add Linter and gitignore file
KanoCode/Hello-world pull request #1
Opened 2022-01-04 15:54 UTC by KanoCode

I have add linter for debugging and clear codes.
I have add gitignore file for ignoring development files.

2022-01-04 16:28 UTC, aliabbani requested changes
Hi @KanoCode ✋, 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! 

To Highlight! 🟢
You created a new GitHub repo. ✔️
You created a new branch according to the GitHub flow rules. ✔️
The repository looks professional ✔️
You added a .gitignore file. ✔️
Opened your first pull request. ✔️

## Required Changes ♻️ 

Check the comments under the review. 

- [ ] Please add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [ ] Please add a test.md file and please write a simple text inside it "This file should be ignored by git".
- [ ] Please Set up a linter correctly. Please check [this link ](https://github.com/microverseinc/linters-config/tree/master/html-css) for more information. Also, please make sure that the Linter result is green on the pull request. Linter should always report no errors when you submit a future pull request (on this pull request the Stylelint is showing ❌).


## Optional suggestions 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 14:11 UTC, enkog requested changes
Hi @KanoCode 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlight
✅ Linters are set up correctly
✅ Descriptive commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. or contact me on slack with the username @enkodes.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 14:11 UTC, enkog commented on README.md
> +Kanombola Kanombola
- [ ] I suggest you include some necessary content to your README file. This is to ensure professionalism and that visitors of this repository know right away what the project is about.
For instance, the project description should be more descriptive, e.g, This is a project that displays Hello World on a page, practicing the use of gitflow and a pull request etc.
- It would be nice to include the following sections from this [template](https://github.com/microverseinc/readme-template)
- Contributing
- Show your support
- Acknowledgement
- [ ] Also add a link to your social media handles in the Authors section to enable a visitor to view your profiles on other platforms.

2022-01-05 14:11 UTC, enkog commented on .gitignore
> +test.md
- [ ] As stated by the previous reviewer and the project requirement, you are to create a file in your project directory, name it `test.md` and add the text `"This file should be ignored by git"` as the content of this file.

2022-01-06 00:40 UTC, andersonlebon approved these changes
Hi @KanoCode 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing ✔️ 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-06 06:35 UTC, merged